### ISSUE TITLE
Deprecated warning about `allow_overwrite`

### ISSUE THREAD

**Issue by yujunz** [cloudposse/terraform-aws-route53-cluster-zone#21]
```shell
[DEPRECATED] The next major version of the Terraform AWS Provider will require importing existing records
```

See https://github.com/cloudposse/terraform-aws-kops-state-backend/issues/12

**Comment by osterman** [comment]
@yujunz please see https://github.com/cloudposse/terraform-aws-route53-cluster-zone/pull/19 and https://github.com/terraform-providers/terraform-provider-aws/issues/7846

**Comment by osterman** [comment]
Closing as this was fixed in https://github.com/terraform-providers/terraform-provider-aws/issues/7846#issuecomment-481775697
